# Generated by Django 2.2 on 2019-10-20 02:58

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher', models.CharField(max_length=50)),
                ('subject_title', models.CharField(max_length=75)),
                ('period', models.CharField(max_length=3)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(default=datetime.datetime.now, verbose_name='date assigned')),
                ('date_due', models.DateTimeField(default=datetime.datetime(2019, 10, 20, 21, 58, 30, 113028), verbose_name='date due')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('priority', models.IntegerField(choices=[(5, "Don't care"), (4, 'Low'), (3, 'Might as well'), (2, 'Necessary'), (1, 'Red Alert')])),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homework_planner.Subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
